name: Create Module Files for Github Release

on:
  release:
    types: [published]

env:
  PROJECT_URL: "https://github.com/jofelicio/smart-icons"
  LATEST_MANIFEST_URL: "https://github.com/jofelicio/smart-icons/releases/latest/download/module.json"
  RELEASE_MODULE_URL: "https://github.com/jofelicio/smart-icons/releases/download/${{ github.event.release.tag_name }}/module.zip"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Version From Tag
        id: get_version
        uses: CarterChen247/version-retriever@v1

      - name: Update Module Manifest
        uses: cschleiden/replace-tokens@v1
        with:
          files: 'module.json'
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          URL: ${{ env.PROJECT_URL }}
          MANIFEST: ${{ env.LATEST_MANIFEST_URL }}
          DOWNLOAD: ${{ env.RELEASE_MODULE_URL }}

      - name: Create Module Archive
        run: |
          zip -r module.zip module.json scripts/ README.md LICENSE

      - name: Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "module.json, module.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
